### PR TITLE
Added admin features

### LINKED ISSUE #58: Api interface for ssh tunnel management
Suggested features:
kill tunnel, list of active tunnels, number of active tunnels, info about specified tunnel (like in log - 2019/12/14 - 19:34:00 | host.com | 200 |    6.792909ms |   ip  | GET      /api/v2/test) ,tunnel stats with bytes in/out , list of dropped tunnels with timestamp and reason

### PR DESCRIPTION
**Pull request by antoniomika**
Closes #58

### CODE REVIEW

**Comment by fork04** [comment]
Tunnels are unstable in admin_features branch, strange disconnect pattern emerged:
2019/12/23 19:55:07 HTTPS forwarding started: 
2019/12/23 20:05:07 HTTPS forwarding started: 
2019/12/23 20:15:07 HTTPS forwarding started: 
2019/12/23 20:25:07 HTTPS forwarding started: 
2019/12/23 20:35:07 HTTPS forwarding started: 
2019/12/23 20:45:07 HTTPS forwarding started: 
2019/12/23 20:55:07 HTTPS forwarding started: 
2019/12/23 21:05:07 HTTPS forwarding started:

**Comment by antoniomika** [comment]
Hmm that looks like a disconnect every 10 minutes? Is there any relation to idle timeouts?

**Comment by fork04** [comment]
Yes, that was my mistake. Something was wrong in parameters of tunnel, please close this thread.

**Comment by antoniomika** [comment]
Hey @fork04, I think the build tagged `28b9614a16f793b56df9507cd3b8387df6951a4d` should solve the issue with old tunnels sticking around. Let me know if that solves the problem for you.

**Pull request merged**
